---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ17N18" #see SAP Continuous Integration and Delivery service for more build tool version options
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true
  Additional Unit Tests:
    npmExecuteScripts: true
  Malware Scan:
    malwareExecuteScan: true
  Acceptance:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "c96f2572trial_demo-uzmq2u5n"
    cfSpace: "dev"
    cfAppName: "Incident-Management"
    cfCredentialsId: "cf"
    deployType: "standard"
    npmExecuteEndToEndTests: false
  Compliance:
    sonarExecuteScan: true
    sonarCredentialsId: "btp"
  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "c96f2572trial_demo-uzmq2u5n"
    cfSpace: "dev"
    cfAppName: "Incident-Management"
    cfCredentialsId: "cf"
    deployType: "standard"
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  npmExecuteLint:
    failOnError: true
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  sonarExecuteScan:
    host: "https://sonarcloud.io"
    organization: "fredatfair"
    projectKey: "faircg_incident-mgmt"
    environment:
      SONAR_TOKEN: "${{sonarCredentialsId}}"  # Inject token from Jenkins credentials
