---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ17N18" #see SAP Continuous Integration and Delivery service for more build tool version options
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true
  Additional Unit Tests:
    npmExecuteScripts: false
  Malware Scan:
    malwareExecuteScan: false
  Acceptance:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "c96f2572trial_demo-uzmq2u5n"
    cfSpace: "dev"
    cfAppName: "Incident-Management"
    cfCredentialsId: "cf"
    deployType: "standard"
    npmExecuteEndToEndTests: false
  Compliance:
    sonarExecuteScan: true
    sonarCredentialsId: "sonarcloud"
  Release:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "c96f2572trial_demo-uzmq2u5n"
    cfSpace: "dev"
    cfAppName: "Incident-Management"
    cfCredentialsId: "cf"
    deployType: "standard"
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  npmExecuteLint:
    failOnError: true
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  sonarExecuteScan:
    host: "https://sonarcloud.io"
    organization: "fredatfair"
    projectKey: "faircg_incident-mgmt"
    environment:
      SONAR_TOKEN: "${065d0cb74873baff24b863c11c118b60e5e6c7e6}"  # Inject token from Jenkins credentials
