---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ21N22"
  stages:
    Acceptance:
      cfCredentialsId: "cf"
    Release:
      cfCredentialsId: "cf"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Acceptance:
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "c96f2572trial_demo-uzmq2u5n"
    cfSpace: "dev"
    deployType: "standard"
    cloudFoundryDeploy: true
    npmExecuteEndToEndTests: false
  Malware Scan:
    malwareExecuteScan: true
  Release:
    tmsExport: false
    tmsUpload: false
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "c96f2572trial_demo-uzmq2u5n"
    cfSpace: "dev"
    deployType: "standard"
    cloudFoundryDeploy: true
  Additional Unit Tests:
    npmExecuteScripts: true
    runScripts:
    - "test"
  Compliance:
    sonarExecuteScan: true
steps:
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  sonarExecuteScan:
    mode: "SonarQube"
    serverUrl: "https://sonarcloud.io"
    projectKey: "abdulrahmansheikh_incident-management"
    sonarTokenCredentialsId: "sonar-demo-abdul"
  artifactPrepareVersion:
    versioningType: "cloud_noTag"


